// amenitiesIconMap.js
import {
  FaBaby,
  FaSpa,
  FaRunning,
  FaGamepad,
  FaRoad,
  FaBirthdayCake,
  FaArrowAltCircleUp,
  FaPagelines,
  FaSolarPanel,
  FaWater,
  FaDumbbell,
  FaTv,
  FaWifi,
  FaSnowflake,
  FaCarBattery,
  FaShower,
  FaRegBuilding,
  FaLock,
  FaCamera,
  FaPhone,
  FaParking,
  FaSwimmingPool,
  FaUmbrellaBeach,
  FaPlug,
  FaTree,
} from "react-icons/fa";

// Store only the component, NOT <Component /> (no JSX)
export const iconMap = {
  "children's play area": FaBaby,
  "yoga / meditation": FaSpa,
  "jogging track": FaRunning,
  "indoor games": FaGamepad,
  "paved compound": FaRoad,
  "party hall": FaBirthdayCake,
  "lift": FaArrowAltCircleUp,
  "lift(s)": FaArrowAltCircleUp,
  "landscaping & trees": FaPagelines,
  "solar power system": FaSolarPanel,
  "solar power": FaSolarPanel,
  "sewage treatment": FaWater,
  "24x7 water": FaWater,
  "water supply": FaWater,
  "parking": FaParking,
  "visitor parking": FaParking,
  "gymnasium": FaDumbbell,
  "gym": FaDumbbell,
  "clubhouse": FaRegBuilding,
  "tv": FaTv,
  "wi-fi": FaWifi,
  "ac": FaSnowflake,
  "fridge": FaCarBattery,
  "washing machine": FaShower,
  "power backup": FaPlug,
  "security": FaLock,
  "fire safety": FaUmbrellaBeach,
  "garden": FaTree,
  "swimming pool": FaSwimmingPool,
  "cctv": FaCamera,
  "intercom": FaPhone,
  "rainwater harvest": FaWater,
  "covered parking": FaCarBattery,
  "covered car parking": FaCarBattery,
};

// Build default amenities with Icon as the component function, not JSX
export const defaultAmenities = Object.entries(iconMap).map(([label, Icon]) => ({
  label,
  Icon,
}));
